#############################################################################
# Makefile for building: calculator
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  calculator.pro
# Template: app
# Command: /usr/local/Qt-5.5/bin/qmake -o Makefile calculator.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Qt-5.5/include -I/usr/local/Qt-5.5/include/QtWidgets -I/usr/local/Qt-5.5/include/QtGui -I/usr/local/Qt-5.5/include/QtCore -I. -I. -I/usr/local/Qt-5.5/mkspecs/linux-g++
QMAKE         = /usr/local/Qt-5.5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = calculator1.0.0
DISTDIR = /home/han/source_test/Qt/calculator/calculator/.tmp/calculator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.5/lib
LIBS          = $(SUBLIBS) -L/usr/local/Qt-5.5/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/Qt-5.5/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.5/mkspecs/common/unix.conf \
		/usr/local/Qt-5.5/mkspecs/common/linux.conf \
		/usr/local/Qt-5.5/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.5/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.5/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.5/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.5/mkspecs/qconfig.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.5/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.5/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.5/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.5/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.5/mkspecs/features/qt.prf \
		/usr/local/Qt-5.5/mkspecs/features/resources.prf \
		/usr/local/Qt-5.5/mkspecs/features/moc.prf \
		/usr/local/Qt-5.5/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.5/mkspecs/features/uic.prf \
		/usr/local/Qt-5.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.5/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.5/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.5/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.5/mkspecs/features/lex.prf \
		calculator.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = calculator
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = calculator


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: calculator.pro /usr/local/Qt-5.5/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.5/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.5/mkspecs/common/unix.conf \
		/usr/local/Qt-5.5/mkspecs/common/linux.conf \
		/usr/local/Qt-5.5/mkspecs/common/sanitize.conf \
		/usr/local/Qt-5.5/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.5/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.5/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.5/mkspecs/qconfig.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcollision.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3drenderer.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Qt-5.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.5/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.5/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.5/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.5/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.5/mkspecs/features/qt.prf \
		/usr/local/Qt-5.5/mkspecs/features/resources.prf \
		/usr/local/Qt-5.5/mkspecs/features/moc.prf \
		/usr/local/Qt-5.5/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.5/mkspecs/features/uic.prf \
		/usr/local/Qt-5.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.5/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.5/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.5/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.5/mkspecs/features/lex.prf \
		calculator.pro \
		/usr/local/Qt-5.5/lib/libQt5Widgets.prl \
		/usr/local/Qt-5.5/lib/libQt5Gui.prl \
		/usr/local/Qt-5.5/lib/libQt5Core.prl
	$(QMAKE) -o Makefile calculator.pro
/usr/local/Qt-5.5/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.5/mkspecs/common/unix.conf:
/usr/local/Qt-5.5/mkspecs/common/linux.conf:
/usr/local/Qt-5.5/mkspecs/common/sanitize.conf:
/usr/local/Qt-5.5/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.5/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.5/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.5/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.5/mkspecs/qconfig.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcollision.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcollision_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3drenderer.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_3drenderer_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_location.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Qt-5.5/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.5/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.5/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.5/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.5/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.5/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.5/mkspecs/features/default_post.prf:
/usr/local/Qt-5.5/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.5/mkspecs/features/qt.prf:
/usr/local/Qt-5.5/mkspecs/features/resources.prf:
/usr/local/Qt-5.5/mkspecs/features/moc.prf:
/usr/local/Qt-5.5/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.5/mkspecs/features/uic.prf:
/usr/local/Qt-5.5/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.5/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.5/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.5/mkspecs/features/yacc.prf:
/usr/local/Qt-5.5/mkspecs/features/lex.prf:
calculator.pro:
/usr/local/Qt-5.5/lib/libQt5Widgets.prl:
/usr/local/Qt-5.5/lib/libQt5Gui.prl:
/usr/local/Qt-5.5/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile calculator.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/Qt-5.5/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.5/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.5/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5/include/QtCore/qflags.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5/include/QtCore/qobject.h \
		/usr/local/Qt-5.5/include/QtCore/qstring.h \
		/usr/local/Qt-5.5/include/QtCore/qchar.h \
		/usr/local/Qt-5.5/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5/include/QtCore/qlist.h \
		/usr/local/Qt-5.5/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5/include/QtCore/qrect.h \
		/usr/local/Qt-5.5/include/QtCore/qsize.h \
		/usr/local/Qt-5.5/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5/include/QtCore/qpair.h \
		/usr/local/Qt-5.5/include/QtCore/qvector.h \
		/usr/local/Qt-5.5/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5/include/QtGui/qregion.h \
		/usr/local/Qt-5.5/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5/include/QtCore/qline.h \
		/usr/local/Qt-5.5/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5/include/QtGui/qimage.h \
		/usr/local/Qt-5.5/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5/include/QtCore/qhash.h \
		/usr/local/Qt-5.5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5/include/QtGui/qfont.h \
		/usr/local/Qt-5.5/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5/include/QtGui/qevent.h \
		/usr/local/Qt-5.5/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5/include/QtCore/qmap.h \
		/usr/local/Qt-5.5/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5/include/QtCore/qset.h \
		/usr/local/Qt-5.5/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5/include/QtCore/qurl.h \
		/usr/local/Qt-5.5/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5/include/QtCore/qfile.h \
		/usr/local/Qt-5.5/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qicon.h \
		/usr/local/Qt-5.5/include/QtWidgets/QDialog \
		/usr/local/Qt-5.5/include/QtWidgets/qdialog.h \
		/usr/local/Qt-5.5/include/QtWidgets/QLabel \
		/usr/local/Qt-5.5/include/QtWidgets/qlabel.h \
		/usr/local/Qt-5.5/include/QtWidgets/qframe.h \
		/usr/local/Qt-5.5/include/QtWidgets/QLineEdit \
		/usr/local/Qt-5.5/include/QtWidgets/qlineedit.h \
		/usr/local/Qt-5.5/include/QtGui/qtextcursor.h \
		/usr/local/Qt-5.5/include/QtGui/qtextformat.h \
		/usr/local/Qt-5.5/include/QtGui/qpen.h \
		/usr/local/Qt-5.5/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5/include/QtWidgets/QAction \
		/usr/local/Qt-5.5/include/QtWidgets/qaction.h \
		/usr/local/Qt-5.5/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMenuBar \
		/usr/local/Qt-5.5/include/QtWidgets/qmenubar.h \
		/usr/local/Qt-5.5/include/QtWidgets/qmenu.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMessageBox \
		/usr/local/Qt-5.5/include/QtWidgets/qmessagebox.h \
		/usr/local/Qt-5.5/include/QtWidgets/QStatusBar \
		/usr/local/Qt-5.5/include/QtWidgets/qstatusbar.h \
		/usr/local/Qt-5.5/include/QtWidgets/QToolBar \
		/usr/local/Qt-5.5/include/QtWidgets/qtoolbar.h \
		/usr/local/Qt-5.5/include/QtCore/QStringList \
		/usr/local/Qt-5.5/include/QtCore/QString \
		/usr/local/Qt-5.5/include/QtWidgets/QPushButton \
		/usr/local/Qt-5.5/include/QtWidgets/qpushbutton.h \
		/usr/local/Qt-5.5/include/QtWidgets/qabstractbutton.h \
		/usr/local/Qt-5.5/include/QtWidgets/QGridLayout \
		/usr/local/Qt-5.5/include/QtWidgets/qgridlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/qlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/qlayoutitem.h \
		/usr/local/Qt-5.5/include/QtWidgets/qboxlayout.h \
		mainwindow.h
	/usr/local/Qt-5.5/bin/moc $(DEFINES) -I/usr/local/Qt-5.5/mkspecs/linux-g++ -I/home/han/source_test/Qt/calculator/calculator -I/usr/local/Qt-5.5/include -I/usr/local/Qt-5.5/include/QtWidgets -I/usr/local/Qt-5.5/include/QtGui -I/usr/local/Qt-5.5/include/QtCore -I/usr/include/c++/4.8 -I/usr/include/x86_64-linux-gnu/c++/4.8 -I/usr/include/c++/4.8/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Qt-5.5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.5/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.5/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5/include/QtCore/qflags.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5/include/QtCore/qobject.h \
		/usr/local/Qt-5.5/include/QtCore/qstring.h \
		/usr/local/Qt-5.5/include/QtCore/qchar.h \
		/usr/local/Qt-5.5/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5/include/QtCore/qlist.h \
		/usr/local/Qt-5.5/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5/include/QtCore/qrect.h \
		/usr/local/Qt-5.5/include/QtCore/qsize.h \
		/usr/local/Qt-5.5/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5/include/QtCore/qpair.h \
		/usr/local/Qt-5.5/include/QtCore/qvector.h \
		/usr/local/Qt-5.5/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5/include/QtGui/qregion.h \
		/usr/local/Qt-5.5/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5/include/QtCore/qline.h \
		/usr/local/Qt-5.5/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5/include/QtGui/qimage.h \
		/usr/local/Qt-5.5/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5/include/QtCore/qhash.h \
		/usr/local/Qt-5.5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5/include/QtGui/qfont.h \
		/usr/local/Qt-5.5/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5/include/QtGui/qevent.h \
		/usr/local/Qt-5.5/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5/include/QtCore/qmap.h \
		/usr/local/Qt-5.5/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5/include/QtCore/qset.h \
		/usr/local/Qt-5.5/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5/include/QtCore/qurl.h \
		/usr/local/Qt-5.5/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5/include/QtCore/qfile.h \
		/usr/local/Qt-5.5/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qicon.h \
		/usr/local/Qt-5.5/include/QtWidgets/QDialog \
		/usr/local/Qt-5.5/include/QtWidgets/qdialog.h \
		/usr/local/Qt-5.5/include/QtWidgets/QLabel \
		/usr/local/Qt-5.5/include/QtWidgets/qlabel.h \
		/usr/local/Qt-5.5/include/QtWidgets/qframe.h \
		/usr/local/Qt-5.5/include/QtWidgets/QLineEdit \
		/usr/local/Qt-5.5/include/QtWidgets/qlineedit.h \
		/usr/local/Qt-5.5/include/QtGui/qtextcursor.h \
		/usr/local/Qt-5.5/include/QtGui/qtextformat.h \
		/usr/local/Qt-5.5/include/QtGui/qpen.h \
		/usr/local/Qt-5.5/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5/include/QtWidgets/QAction \
		/usr/local/Qt-5.5/include/QtWidgets/qaction.h \
		/usr/local/Qt-5.5/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMenuBar \
		/usr/local/Qt-5.5/include/QtWidgets/qmenubar.h \
		/usr/local/Qt-5.5/include/QtWidgets/qmenu.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMessageBox \
		/usr/local/Qt-5.5/include/QtWidgets/qmessagebox.h \
		/usr/local/Qt-5.5/include/QtWidgets/QStatusBar \
		/usr/local/Qt-5.5/include/QtWidgets/qstatusbar.h \
		/usr/local/Qt-5.5/include/QtWidgets/QToolBar \
		/usr/local/Qt-5.5/include/QtWidgets/qtoolbar.h \
		/usr/local/Qt-5.5/include/QtCore/QStringList \
		/usr/local/Qt-5.5/include/QtCore/QString \
		/usr/local/Qt-5.5/include/QtWidgets/QPushButton \
		/usr/local/Qt-5.5/include/QtWidgets/qpushbutton.h \
		/usr/local/Qt-5.5/include/QtWidgets/qabstractbutton.h \
		/usr/local/Qt-5.5/include/QtWidgets/QGridLayout \
		/usr/local/Qt-5.5/include/QtWidgets/qgridlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/qlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/qlayoutitem.h \
		/usr/local/Qt-5.5/include/QtWidgets/qboxlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/QApplication \
		/usr/local/Qt-5.5/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.5/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.5/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.5/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.5/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.5/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.5/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.5/include/QtCore/qglobal.h \
		/usr/local/Qt-5.5/include/QtCore/qconfig.h \
		/usr/local/Qt-5.5/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.5/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.5/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.5/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.5/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.5/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.5/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.5/include/QtCore/qlogging.h \
		/usr/local/Qt-5.5/include/QtCore/qflags.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.5/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.5/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.5/include/QtCore/qglobalstatic.h \
		/usr/local/Qt-5.5/include/QtCore/qmutex.h \
		/usr/local/Qt-5.5/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.5/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.5/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.5/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.5/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.5/include/QtCore/qobject.h \
		/usr/local/Qt-5.5/include/QtCore/qstring.h \
		/usr/local/Qt-5.5/include/QtCore/qchar.h \
		/usr/local/Qt-5.5/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.5/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.5/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.5/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.5/include/QtCore/qlist.h \
		/usr/local/Qt-5.5/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.5/include/QtCore/qiterator.h \
		/usr/local/Qt-5.5/include/QtCore/qbytearraylist.h \
		/usr/local/Qt-5.5/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.5/include/QtCore/qregexp.h \
		/usr/local/Qt-5.5/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.5/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.5/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.5/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.5/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.5/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.5/include/QtCore/qisenum.h \
		/usr/local/Qt-5.5/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.5/include/QtCore/qmargins.h \
		/usr/local/Qt-5.5/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.5/include/QtCore/qrect.h \
		/usr/local/Qt-5.5/include/QtCore/qsize.h \
		/usr/local/Qt-5.5/include/QtCore/qpoint.h \
		/usr/local/Qt-5.5/include/QtGui/qpalette.h \
		/usr/local/Qt-5.5/include/QtGui/qcolor.h \
		/usr/local/Qt-5.5/include/QtGui/qrgb.h \
		/usr/local/Qt-5.5/include/QtGui/qbrush.h \
		/usr/local/Qt-5.5/include/QtCore/qpair.h \
		/usr/local/Qt-5.5/include/QtCore/qvector.h \
		/usr/local/Qt-5.5/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.5/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.5/include/QtGui/qregion.h \
		/usr/local/Qt-5.5/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.5/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.5/include/QtCore/qline.h \
		/usr/local/Qt-5.5/include/QtGui/qtransform.h \
		/usr/local/Qt-5.5/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.5/include/QtGui/qimage.h \
		/usr/local/Qt-5.5/include/QtGui/qpixelformat.h \
		/usr/local/Qt-5.5/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.5/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.5/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.5/include/QtCore/qhash.h \
		/usr/local/Qt-5.5/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.5/include/QtGui/qfont.h \
		/usr/local/Qt-5.5/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.5/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.5/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.5/include/QtGui/qcursor.h \
		/usr/local/Qt-5.5/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.5/include/QtGui/qevent.h \
		/usr/local/Qt-5.5/include/QtCore/qvariant.h \
		/usr/local/Qt-5.5/include/QtCore/qmap.h \
		/usr/local/Qt-5.5/include/QtCore/qdebug.h \
		/usr/local/Qt-5.5/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.5/include/QtCore/qlocale.h \
		/usr/local/Qt-5.5/include/QtCore/qset.h \
		/usr/local/Qt-5.5/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.5/include/QtCore/qurl.h \
		/usr/local/Qt-5.5/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.5/include/QtCore/qfile.h \
		/usr/local/Qt-5.5/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.5/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.5/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.5/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.5/include/QtGui/qicon.h \
		/usr/local/Qt-5.5/include/QtWidgets/QDialog \
		/usr/local/Qt-5.5/include/QtWidgets/qdialog.h \
		/usr/local/Qt-5.5/include/QtWidgets/QLabel \
		/usr/local/Qt-5.5/include/QtWidgets/qlabel.h \
		/usr/local/Qt-5.5/include/QtWidgets/qframe.h \
		/usr/local/Qt-5.5/include/QtWidgets/QLineEdit \
		/usr/local/Qt-5.5/include/QtWidgets/qlineedit.h \
		/usr/local/Qt-5.5/include/QtGui/qtextcursor.h \
		/usr/local/Qt-5.5/include/QtGui/qtextformat.h \
		/usr/local/Qt-5.5/include/QtGui/qpen.h \
		/usr/local/Qt-5.5/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.5/include/QtWidgets/QAction \
		/usr/local/Qt-5.5/include/QtWidgets/qaction.h \
		/usr/local/Qt-5.5/include/QtWidgets/qactiongroup.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMenuBar \
		/usr/local/Qt-5.5/include/QtWidgets/qmenubar.h \
		/usr/local/Qt-5.5/include/QtWidgets/qmenu.h \
		/usr/local/Qt-5.5/include/QtWidgets/QMessageBox \
		/usr/local/Qt-5.5/include/QtWidgets/qmessagebox.h \
		/usr/local/Qt-5.5/include/QtWidgets/QStatusBar \
		/usr/local/Qt-5.5/include/QtWidgets/qstatusbar.h \
		/usr/local/Qt-5.5/include/QtWidgets/QToolBar \
		/usr/local/Qt-5.5/include/QtWidgets/qtoolbar.h \
		/usr/local/Qt-5.5/include/QtCore/QStringList \
		/usr/local/Qt-5.5/include/QtCore/QString \
		/usr/local/Qt-5.5/include/QtWidgets/QPushButton \
		/usr/local/Qt-5.5/include/QtWidgets/qpushbutton.h \
		/usr/local/Qt-5.5/include/QtWidgets/qabstractbutton.h \
		/usr/local/Qt-5.5/include/QtWidgets/QGridLayout \
		/usr/local/Qt-5.5/include/QtWidgets/qgridlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/qlayout.h \
		/usr/local/Qt-5.5/include/QtWidgets/qlayoutitem.h \
		/usr/local/Qt-5.5/include/QtWidgets/qboxlayout.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

